package pl.paweln.agricola.action;

public enum ActionType {
    BUILD_ROOMS_OR_BARNS,
    STARTING_PLAYER,
    TAKE_1_GRAIN,
    PLOW_1_FIELD,
    BUILD_1_BARN_OR_BAKE_BREAD,
    DAY_LABOUR,
    TAKE_WOOD_3_ACC,
    TAKE_CLAY_1_ACC,
    TAKE_REED_1_ACC,
    TAKE_WOOD_2_ACC_3P_4P,
    TAKE_1R_OR_1S_PLUS_1F_3P, // 3P
    TAKE_CLAY_1_ACC_3P,
    TAKE_WOOD_1_ACC_3P_4P,
    TAKE_1R_1S_1F_4P,
    TAKE_WOOD_4_ACC_5P,
    TAKE_CLAY_3_ACC_5P,
    TAKE_FOOD_OR_BUILD_1_ROOM_5P,
    TAKE_FOOD_4P,
    TAKE_ANIMALS,
    TAKE_1R_1S_1W_5P,
    FAMILY_GROW_5P, // starting from round 5
    BUILD_FENCES,
    BUILD_MAJOR_IMPROVEMENT,
    TAKE_SHEEP,
    SOW_OR_BAKE_BREAD,
    RENOVATION_AND_BUILD_IMPROVEMENT,
    FAMILY_GROW,
    TAKE_STONE_1_ACC_PH2,
    TAKE_VEGETABLE,
    TAKE_WILD_BOAR,
    TAKE_COW,
    TAKE_STONE_1_ACC_PH3,
    PLOW_1_FIELD_OR_SOW,
    FAMILY_GROW_DESPITE_LACK_OF_PLACE,
    RENOVATION_AND_BUILD_FENCES
}
